//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tb_cartao
{
    public int cd_cartao { get; set; }
    public string nm_cartao { get; set; }
    public Nullable<System.DateTime> dt_validade { get; set; }
    public string ds_tipo { get; set; }
    public int cd_user { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }
}

public partial class tb_parcelas
{
    public int cd_parcela { get; set; }
    public int nr_parcelas { get; set; }
    public int cd_user { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }
}

public partial class tb_segmento
{
    public int cd_segmento { get; set; }
    public string nm_segmento { get; set; }
    public Nullable<int> cd_user { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }
}

public partial class tb_usuario
{
    public tb_usuario()
    {
        this.tb_cartao = new HashSet<tb_cartao>();
        this.tb_segmento = new HashSet<tb_segmento>();
        this.tb_parcelas = new HashSet<tb_parcelas>();
    }

    public int cd_user { get; set; }
    public string nm_user { get; set; }
    public string nr_senha { get; set; }
    public string nm_email { get; set; }
    public string cpf { get; set; }

    public virtual ICollection<tb_cartao> tb_cartao { get; set; }
    public virtual ICollection<tb_segmento> tb_segmento { get; set; }
    public virtual ICollection<tb_parcelas> tb_parcelas { get; set; }
}
